#ifndef __INC_AFFECT_H
#define __INC_AFFECT_H

class CAffect
{
	public:
		DWORD	dwType;
		BYTE    bApplyOn;
		long long    lApplyValue;
		DWORD   dwFlag;
		long	lDuration;
		long	lSPCost;

		static CAffect* Acquire();
		static void Release(CAffect* p);
};

enum EAffectTypes
{
	AFFECT_NONE,

	AFFECT_MOV_SPEED		= 200,
	AFFECT_ATT_SPEED,
	AFFECT_ATT_GRADE,
	AFFECT_INVISIBILITY,
	AFFECT_STR,
	AFFECT_DEX,			// 205
	AFFECT_CON,
	AFFECT_INT,
	AFFECT_FISH_MIND_PILL,

	AFFECT_POISON,
	AFFECT_STUN,		// 210
	AFFECT_SLOW,
	AFFECT_DUNGEON_READY,
	AFFECT_DUNGEON_UNIQUE,

	AFFECT_BUILDING,
	AFFECT_REVIVE_INVISIBLE,	// 215
	AFFECT_FIRE,
	AFFECT_CAST_SPEED,
	AFFECT_HP_RECOVER_CONTINUE,
	AFFECT_SP_RECOVER_CONTINUE,

	AFFECT_POLYMORPH,		// 220
	AFFECT_MOUNT,

	AFFECT_WAR_FLAG,		// 222

	AFFECT_BLOCK_CHAT,		// 223
	AFFECT_CHINA_FIREWORK,

	AFFECT_BOW_DISTANCE,	// 225
	AFFECT_DEF_GRADE,		// 226
#ifdef ENABLE_WOLFMAN_CHARACTER
	AFFECT_BLEEDING,		// 227
#endif

	AFFECT_PREMIUM_START	= 500,
	AFFECT_EXP_BONUS		= 500,
	AFFECT_ITEM_BONUS		= 501,
	AFFECT_SAFEBOX		= 502,  // PREMIUM_SAFEBOX,
	AFFECT_AUTOLOOT		= 503,	// PREMIUM_AUTOLOOT,
	AFFECT_FISH_MIND		= 504,	// PREMIUM_FISH_MIND,
	AFFECT_MARRIAGE_FAST	= 505,
	AFFECT_GOLD_BONUS		= 506,
	AFFECT_PREMIUM_END		= 509,

	AFFECT_MALL			= 510,
	AFFECT_NO_DEATH_PENALTY	= 511,
	AFFECT_SKILL_BOOK_BONUS	= 512,
	AFFECT_SKILL_NO_BOOK_DELAY	= 513,

	AFFECT_HAIR	= 514,
	AFFECT_COLLECT = 515,
	AFFECT_EXP_BONUS_EURO_FREE = 516,
	AFFECT_EXP_BONUS_EURO_FREE_UNDER_15 = 517,
	AFFECT_UNIQUE_ABILITY = 518,

	AFFECT_CUBE_1,
	AFFECT_CUBE_2,
	AFFECT_CUBE_3,
	AFFECT_CUBE_4,
	AFFECT_CUBE_5,
	AFFECT_CUBE_6,
	AFFECT_CUBE_7,
	AFFECT_CUBE_8,
	AFFECT_CUBE_9,
	AFFECT_CUBE_10,
	AFFECT_CUBE_11,
	AFFECT_CUBE_12,

	AFFECT_BLEND,

	AFFECT_HORSE_NAME,
	AFFECT_MOUNT_BONUS,

	AFFECT_AUTO_HP_RECOVERY = 534,
	AFFECT_AUTO_SP_RECOVERY = 535,

	AFFECT_DRAGON_SOUL_QUALIFIED = 540,
	AFFECT_DRAGON_SOUL_DECK_0 = 541,
	AFFECT_DRAGON_SOUL_DECK_1 = 542,
#ifdef ENABLE_DS_SET
	AFFECT_DS_SET			  = 543,
#endif
	AFFECT_RAMADAN_ABILITY = 300,
	AFFECT_RAMADAN_RING	   = 301,

	AFFECT_NOG_ABILITY = 302,
	AFFECT_HOLLY_STONE_POWER = 303,

#if defined(__EXTENDED_BLEND_AFFECT__) || defined(__BLEND_AFFECT__)
	AFFECT_BLEND_POTION_1 = 304, // Critical
	AFFECT_BLEND_POTION_2 = 305, // Penetration
	AFFECT_BLEND_POTION_3 = 306, // Attack Speed
	AFFECT_BLEND_POTION_4 = 307, // Magic Resist
	AFFECT_BLEND_POTION_5 = 308, // Attack Value
	AFFECT_BLEND_POTION_6 = 309, // Defense
	AFFECT_ENERGY = 310,
	AFFECT_DRAGON_GOD_1 = 311, // Max HP.
	AFFECT_DRAGON_GOD_2 = 312, // Max SP.
	AFFECT_DRAGON_GOD_3 = 313, // Attack Value
	AFFECT_DRAGON_GOD_4 = 314, // Defense
	AFFECT_CRITICAL = 315,
	AFFECT_PENETRATE = 316,
	AFFECT_ATTACK_SPEED = 317,
	AFFECT_MOVE_SPEED = 318,
	AFFECT_ATT_WATER = 319,
	AFFECT_DEF_WATER = 320,
	AFFECT_FISH1,
	AFFECT_FISH2,
	AFFECT_FISH3,
	AFFECT_FISH4,
	AFFECT_FISH5,
	AFFECT_FISH6,
	AFFECT_FISH7,
	AFFECT_FISH8,
	AFFECT_FISH9,
	AFFECT_FISH10,
	AFFECT_FISH11,
	AFFECT_FISH12,
	AFFECT_FISH13,
	AFFECT_FISH14,
	AFFECT_BLEND_MONSTERS,
#endif
#if defined(__SHIP_DEFENSE__)
	AFFECT_DEFENSEWAVE_LASER = 573,
#endif
#ifdef ENABLE_OFFLINESHOP_SYSTEM
	AFFECT_DECORATION = 703,
#endif
#ifdef ENABLE_MULTI_FARM_BLOCK
	AFFECT_MULTI_FARM_PREMIUM = 704,
#endif
#ifdef __RENEWAL_CRYSTAL__
	AFFECT_CRYSTAL = 709,
#endif
#ifdef RENEWAL_PICKUP_AFFECT
	AFFECT_PICKUP_ENABLE = 810,
	AFFECT_PICKUP_DEACTIVE = 811,
#endif
#ifdef __RENEWAL_BRAVE_CAPE__
	AFFECT_BRAVE_CAPE = 813,
#endif
	AFFECT_PARTY = 814,
	AFFECT_NAME_MOUNT = 815,
	AFFECT_NAME_PET = 816,

	AFFECT_SINGLE_BONUS_URIEL = 817,
	AFFECT_SINGLE_BONUS_URIEL_DELAY = 818,

	AFFECT_LOCK_1 = 819,
	AFFECT_LOCK_2 = 820, 

#ifdef METINSTONES_QUEUE
	AFFECT_AUTO_METIN_FARM = 821,
	AFFECT_THIEF_GLOVES_STONES = 822,
	AFFECT_THIEF_GLOVES_BOSSES = 823,
#endif

	AFFECT_QUEST_START_IDX = 1000
};

enum EAffectBits
{
	AFF_NONE,

	AFF_YMIR,
	AFF_INVISIBILITY,
	AFF_SPAWN,

	AFF_POISON,
	AFF_SLOW,
	AFF_STUN,

	AFF_DUNGEON_READY, 
	AFF_DUNGEON_UNIQUE,

	AFF_BUILDING_CONSTRUCTION_SMALL,
	AFF_BUILDING_CONSTRUCTION_LARGE,
	AFF_BUILDING_UPGRADE,

	AFF_MOV_SPEED_POTION,
	AFF_ATT_SPEED_POTION,

	AFF_FISH_MIND,

	AFF_JEONGWIHON, 
	AFF_GEOMGYEONG,
	AFF_CHEONGEUN,
	AFF_GYEONGGONG,
	AFF_EUNHYUNG,
	AFF_GWIGUM,
	AFF_TERROR,
	AFF_JUMAGAP,
	AFF_HOSIN,
	AFF_BOHO,
	AFF_KWAESOK,
	AFF_MANASHIELD,
	AFF_MUYEONG,
	AFF_REVIVE_INVISIBLE,
	AFF_FIRE,
	AFF_GICHEON,
	AFF_JEUNGRYEOK,
	AFF_TANHWAN_DASH,
	AFF_PABEOP,
	AFF_CHEONGEUN_WITH_FALL,
	AFF_POLYMORPH,
	AFF_WAR_FLAG1,
	AFF_WAR_FLAG2,
	AFF_WAR_FLAG3,

	AFF_CHINA_FIREWORK,
	AFF_HAIR,
	AFF_GERMANY,

	AFF_DS,

	AFF_BLEEDING,
	AFF_RED_POSSESSION,
	AFF_BLUE_POSSESSION,

	AFF_STATUE1,
	AFF_STATUE2,
	AFF_STATUE3,
	AFF_STATUE4,

	AFF_SOUL_RED,
	AFF_SOUL_BLUE,
	AFF_SOUL_MIX,

	AFF_CHEONUN,
	AFF_BUFFI_HOSIN,
	AFF_BUFFI_GICHEON,
	AFF_BUFFI_KWAESOK,
	AFF_BUFFI_JEUNGRYEOK,
	
	AFF_CHUNWOON_MOOJUK,

	AFF_DEFENSE_WAVE_LASER,
	AFF_LEADERSHIP,
	AFF_LOCK_1,
	AFF_LOCK_2,
	AFF_BITS_MAX
};

extern void SendAffectAddPacket(LPDESC d, CAffect * pkAff);

// AFFECT_DURATION_BUG_FIX
enum AffectVariable
{
	INFINITE_AFFECT_DURATION = 2147483647-1
};
// END_AFFECT_DURATION_BUG_FIX

#endif
//martysama0134's 7f12f88f86c76f82974cba65d7406ac8
